# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'Original Assets', '/vendor']
timezone: 'Africa/Abidjan'

# Miscellaneous
# googleMapsAPIKey: "AIzaSyAvGdd7lRTgZrGDwURX87xxBuina1LL43k"

# Site Settings
title: "State of the Map Afria 2019"
email: "sotmafrica@gmail.com"
description: "State of the Map Africa (SotM Africa) is a regional state of the map conference for Africa."
baseurl: ""
url: http://2019.stateofthemap.africa
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-134637244-1" # Conference tracking ID
googleAnalyticsSiteUrl: "2019.stateofthemap.africa" 
siteVerification: "ovUOjOoTbBjb5tDN_wsULXG5fuww734DFxZt8zCe43g"

# Organizer Info
organizerName: "OpenStreetMap Africa, OpenStreetMap Cote D'Ivore"
organizerAlternateName: "SOTM Africa 2019"
organizerDescription: "Open and volunteer geo community who creates maps that saves lives and share experience about open data."
organizerEmail: "sotmafrica@gmail.com"
# organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://openstreetmap.africa"

# Head
metaKeywords: "event, osm, openstreetmap, sotm, sotmafrica, maps, opendata, conferene, africa"
twitterAccount: "@sotmafrica"
# socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
# socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
# socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: ""
c4sponsorsUrl: "/sponsorship/"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/blog", text: "Blog"}
  - {permalink: "/calls", text: "Call for Participation"}
  - {permalink: "/program/", text: "Schedule"}
 # - {permalink: "/speakers/", text: "Speakers"}
 # - {permalink: "/#tickets", text: "Tickets"}
 # - {permalink: "/#partners", text: "Sponsors"}
  - {permalink: "/about/", text: "About"}
  - {permalink: "/logistics/", text: "Logistics"}
  - {permalink: "/faq/", text: "FAQ"}
bottomNavigationLinks:
 - {link: "/sponsorship/", text: "Become a Sponsor"}
rightNavigationButtons:
 - {link: "/sponsorship/", text: "Become a Sponsor"}

# Hero Block
# Hero Block
heroImage: "her0.jpg"
heroTitle: "SOTM <typeout> 2019"
eventDate: "Grand-Bassam, Ivory Coast | 22-24 November 2019 | Transforming lives through mapping"
typeoutTextValues: '"", "Africa", "Grand-Bassam", "Ivory Coast"'
typeoutFallback: "Africa"
heroButtons:
 - {permalink: "/calls", text: "Submit a talk"}
 - {permalink: "/calls", text: "Scholarship Application"}

# About Block
aboutTitle: "About SOTM Africa 2019"
aboutSubTitle: "Join us for 3 days of learning, sharing and fun!"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "<p>SOTM Africa will bring together participants from around the world to discuss challenges, learn, and celebrate many years of mapping together.</p>" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience. Come, learn and share!" }
 - {title: "Community", image: "community.jpg", text: "Meet the community and have fun!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Swift"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from Boston and beyond"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "catch the videos later!"} #TODO: tagline appropriate?


# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Featured Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "VITIB"
eventLocationLink: "https://www.huntingtontheatre.org/about/venue/pavilion/"
eventStreetAddress: "Calderwood Pavilion<br />527 Tremont Street"
eventAddressLocality: "Boston"
eventAddressLocalityRegion: "MA"
eventPostalCode: "02116"
eventAddressCountry: "USA"
eventStartTime: "9:00 am"
eventDoorTime: "09:00"
eventEndTime: "6:00 pm"
eventPlaceCoordinates: "42.344797, -71.070950"
mapCenterCoordinates: "42.344848, -71.072060"
mapMobileCenterCoordinates: "42.344848, -71.072060"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Grand-Bassam"
venueFeatures: ["Ivory Coast"]

# Tweets Feed Block
# TODO: need to set up tweetledee or delete this section https://github.com/tweetledee/tweetledee
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "sotm=africa?"
twitterHashTag: "sotmafrica"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Supporters Block
supportersTitle: "Supporters"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://sotmafrica.us15.list-manage.com/subscribe/post"
subscribeHiddenU: "5fae4e4446decef8838e19ef6"
subscribeHiddenId: "f469fd9019"
subscribeInfo: "Subscribe to our mailing list"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "Conference ticket purchase includes 2 full days of sessions (June 18thâ€“19th) and exhibitor booths, a ticket to the official conference party on June 18th for you and a guest, morning snack, lunch, and afternoon snack on both days."
ticketsOffers:
 -
   name: "Student"
   price: "99"
   priceCurrency: "USD"
   buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2018-tickets-37370599469#tickets"
   buyButtonText: "Buy Now"
   additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund."
   validFrom: "2018-1-1T00:00"
   validThrough: "2018-06-18T9:00"
   soldOut: false
   disabled: false
   soldOutText: "Sold Out"
 -
   name: "Group Ticket"
   price: "299"
   priceCurrency: "USD each"
   buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2018-tickets-37370599469#tickets"
   buyButtonText: "Buy Now"
   additionalInfo: "May be purchased in groups of 4."
   validFrom: "2018-1-1T00:00"
   validThrough: "2018-06-08T23:59"
   soldOut: false
   disabled: false
 -
  name: "In Time Bird"
  price: "499"
  priceCurrency: "USD"
  buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2018-tickets-37370599469#tickets"
  buyButtonText: "Buy Now"
  additionalInfo: "Conference ticket purchase includes 2 full days of sessions (June 18th - 19th) and exhibitor booths, a ticket to the official conference party on June 18th, morning snack, lunch and afternoon snack on both days."
  validFrom: "2018-04-11T00:00"
  validThrough: "2018-06-08T23:59"
  soldOut: false
  disabled: false
 -
  name: "Regular Ticket"
  price: "599"
  priceCurrency: "USD"
  buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2018-tickets-37370599469#tickets"
  buyButtonText: "Buy Now"
  additionalInfo: "Conference ticket purchase includes 2 full days of sessions (June 18th - 19th) and exhibitor booths, a ticket to the official conference party on June 18th, morning snack, lunch and afternoon snack on both days."
  validFrom: "2018-06-09T00:00"
  validThrough: "2018-06-16T23:59"
  soldOut: false
  disabled: true

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=sotmafrica", icon: "twitter"}
 - {link: "https://www.facebook.com/sotmafrica", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:sotmafrica@gmail.com", text: "sotmafrica@gmail.com"}
 -
  title: "Links"
  links:
   - {permalink: "https://wiki.openstreetmap.org/wiki/State_of_the_Map_Africa_2019", text: "Wiki page"}
   - {permalink: "//openstreetmap.africa", text: "OSM Africa"}
   - {permalink: "/code-of-conduct/", text: "Code of Conduct"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: ""

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "5.22965, -3.75829"
logisticsMapMobileCenterCoordinates: "5.22965, -3.75829"
logisticsMapAutoDirections: false

# Location
locationLatLon: 5.22965, -3.75829
locationCenterLatLon: 5.22965, -3.75829
zoomLevel: 14

# Logistics Direction Details Block
directionDetailsImage: "grand-bassam.jpg"
directionDetailsTitle: "Get around Grand-Bassam"
directionDetailsCards:
 - {title: "From the Airport", information: 'Coming soon..'}
 - {title: "Public Transit", information: 'Coming soon..'}
 - {title: "Hotels", information: 'Coming soon..'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Travel"
    links:
     - {link: "https://www.aeroport-abidjan.com/visa_cote_d_ivoire.php", text: "Visa"}
     - {link: "https://en.wikivoyage.org/wiki/Grand-Bassam", text: "Wikivoyage"}
     - {link: "#", text: "Getting to venue"}
     - {link: "#", text: "Getting around venue"}
   -
    title: "Registration"
    links:
     # - {link: "", text: "Buy Tickets"}
     - Coming soon ...
   -
    title: "Attendance Details"
    links:
      - Coming soon...
     # - {link: "https://www.eventbrite.com/e/swiftfest-2018-tickets-37370599469", text: "Event Info"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: ""
